steps:
  - pwsh: |
      git config --global user.name "AzureDevOps Agent"
      git tag "$(Build.BuildNumber)" --force
      git push origin "$(Build.BuildNumber)" --force
      Write-Output "Tagging $(Build.Repository.Name) with $(Build.BuildNumber)"
    displayName:  set git tag