<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrandUp.Website.Abstractions\BrandUp.Website.Abstractions.csproj" />
	</ItemGroup>

</Project>